* sync.nvim

A Neovim plugin for syncing local and remote directories using ~rsync~.
It helps with automating the deployment process by providing options to sync files between the local and remote machines, either on-demand or automatically.

** Features

- Sync local and remote directories using ~rsync~.
- Auto-sync on file save (configurable).
- Dry-run mode for testing synchronization.
- Auto-load configuration from ~.deploy.lua~ when opening files.

** Setup

1. Install the plugin using your preferred plugin manager, e.g., [[https://github.com/folke/lazy.nvim][lazy.nvim]]:
    #+BEGIN_SRC lua
    return {
    	"mrkatebzadeh/sync.nvim",
    	config = function()
    		require("sync").setup({
    			auto_start = false,
          -- ... the rest of options
    		})
    	end,
    }
    #+END_SRC

2. Use ~SyncInit~ command to create a ~.deploy.lua~ file at the root of your project to specify sync settings:

   #+BEGIN_SRC lua
   return {
      root_local = "~/MyProject",
      root_remote = "remotehost:~/MyProject",
      auto_sync = true,
      ignore = { ".git" },
   }
   #+END_SRC

** Commands

- ~SyncInit~ - Create the ~.deploy.lua~ file in the /project's root/ (where ~.git~ exists).
- ~SyncNow~ - Sync the directories immediately.
- ~SyncDryRun~ - Run a dry-run to preview the sync without making changes.
- ~SyncReloadConfig~ - Reload the config from .deploy.lua

** License

This plugin is licensed under the GNU General Public License v2. See [[LICENSE][LICENSE]] for details.
